#!/bin/bash
git merge stage && git --work-tree=../ checkout -f
repo=$(pwd) && cd /etc/copal && . state/globals.sh
bash cycle.sh "cd $repo && git --work-tree=../ pull ssh://$DEV_USER@$NODE_IP$repo" -e
